version: "3.8"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /Users/jocampo/Documents/dev/db/url-shortener:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  python:
    build: ./server/python
    volumes:
      - ./server/python:/code
    ports:
      - 8000:8000
    environment:
      - TBD=kekw
    depends_on:
      - db
